### ISSUE TITLE
Be able to use aliases.

### ISSUE THREAD

**Issue by trotsallt** [rappen/FetchXMLBuilder#1039]
Hi, thx for a great tool. A question, if I use aliases on fields they don't seem to show up at all in the result.
Am I doing something wrong or is this something that could be fixed?
![image](https://github.com/rappen/FetchXMLBuilder/assets/166593044/e25a11f1-6a7f-458f-bc3b-02a514b61826)
![image](https://github.com/rappen/FetchXMLBuilder/assets/166593044/c771fcf0-4def-4af4-9ce8-3b6ec0541e3d)

I can run this in the fetchxml tester tool though and get the result with fields named.
![image](https://github.com/rappen/FetchXMLBuilder/assets/166593044/18a04d98-55cc-4cf8-92e8-7c9b47c78462)

**Comment by rappen** [comment]
Hi

First, normally we don't use alias unless you do aggregated queries. But I know, according to [the docs, it works](https://learn.microsoft.com/power-apps/developer/data-platform/fetchxml/select-columns#column-aliases).
So it works, and it works for me at least.

Second screenshot: I have the same issues, in the "raw" result, it doesn't show up. If I remove alias from attributes, it shows up.
At this point I'm not sure if the issue is in FXB or in the SDK. But I see that the SDK has [deprecated that request](https://learn.microsoft.com/dotnet/api/microsoft.crm.sdk.messages.executefetchrequest.-ctor). 

Third screenshot: FetchXml Tester always just shows the data returned. In my grid view it's trying to show it with correct column name etc. which my be something I should try to show alias name instead.

My query when I'm trying:
```xml
<fetch>
  <entity name='contact'>
    <attribute name='fullname' alias='ThePerson' />
    <attribute name='ownerid' alias='TheOwner' />
    <link-entity name='systemuser' from='systemuserid' to='ownerid' alias='USER'>
      <attribute name='lastname' alias='TheOwnerLastname' />
    </link-entity>
  </entity>
</fetch>
```

Result in a "not friendly" view:
![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/2103f555-7cf7-4f5c-858c-5eb207b1beb4)

Result in a "friendly" view:
![image](https://github.com/rappen/FetchXMLBuilder/assets/2572253/3e32b178-68d4-4088-a63a-4509ebdae7ba)

Raw result:
```xml
<resultset morerecords='0' paging-cookie='&lt;cookie page="1"&gt;&lt;contactid last="{41388504-F44A-EC11-8C62-6045BD8F5259}" first="{5E7F1131-2DAD-EC11-9840-000D3A2BC35A}" /&gt;&lt;/cookie&gt;'>
  <result>
    <contactid>{5E7F1131-2DAD-EC11-9840-000D3A2BC35A}</contactid>
  </result>
  <result>
    <contactid>{DBD00E67-6E63-EC11-8F8F-000D3A2D112C}</contactid>
  </result>
  <result>
    <contactid>{B8706CDA-EEE4-EC11-BB3C-000D3A3A8AD0}</contactid>
  </result>
  <result>
    <contactid>{2355B467-533E-EC11-8C63-000D3A4A08D0}</contactid>
  </result>
  ...
```

Querying without aliases:
```xml
<resultset morerecords='0' paging-cookie='&lt;cookie page="1"&gt;&lt;contactid last="{41388504-F44A-EC11-8C62-6045BD8F5259}" first="{5E7F1131-2DAD-EC11-9840-000D3A2BC35A}" /&gt;&lt;/cookie&gt;'>
  <result>
    <fullname>Anders Rapp</fullname>
    <ownerid dsc='' type='8' yomi='Jonas Rapp' name='Jonas Rapp'>{B5863A5C-5934-EC11-8C65-000D3A217588}</ownerid>
    <contactid>{5E7F1131-2DAD-EC11-9840-000D3A2BC35A}</contactid>
    <USER.lastname>Rapp</USER.lastname>
  </result>
  <result>
    <fullname>Frederick W. Sturckow</fullname>
    <ownerid dsc='' type='8' yomi='Jonas Rapp' name='Jonas Rapp'>{B5863A5C-5934-EC11-8C65-000D3A217588}</ownerid>
    <contactid>{DBD00E67-6E63-EC11-8F8F-000D3A2D112C}</contactid>
    <USER.lastname>Rapp</USER.lastname>
  </result>
  ...
```

**Comment by rappen** [comment]
I was thinking about any Alias shall override DisplayName in "Friendly" view, and make sure LogicalName are shown in "raw" view.
Do you agree with my idea?

I'm working now for solving a bunch of new features, and fixing some bugs. We'll see if I solve this one for this release.

**Comment by rappen** [comment]
Sorry, I misunderstood your request, I was thinking about View Result and *not* Friendly.

I have investigating more regarding `ExecuteFetchRequest` and it just don't return attributes that have an alias. Period.
We shouldn't use it.

I have improved the View Result though, with better handling of Alias.

I believe this issue is now "solved", as far as possible.
Please reopen it if needed!
