### ISSUE TITLE
Open View does not work with FetchXMLBuilder in multiple tabs

### ISSUE THREAD

**Issue by simes1** [rappen/FetchXMLBuilder#230]
I noticed today that if I open a view in FetchXMLBuilder in one tab (connected to one instance) then open the same view in another tab (connected to a different instance) the XML from the first tab appears to be used.  The views appeared the same in FetchXMLBuilder even though in my case they most definitely weren't.

I was trying to find differences in views between Test and Live - FetchXMLBuilder gave very confusing results until I figured out what was happening.

--
Simon

**Comment by rappen** [comment]
So, you have two tabs in XTB open with FXB, tab 1 and 2.
Tab 1 is connected to org A and tab 2 is connected to org B.

You open a view in tab 1.
Then you open a view (same entity and view name) in tab 2.

Expect to see different FetchXML (since the views are indeed different).
But you see the same FetchXML.

Is that correctly understood by me?

**Comment by simes1** [comment]
Yes – that is correct.

However, I now realise it is actually worse than that – pick another view for that entity in tab 2 and it is also from org A not org B.

Regards

--
Simon

**Comment by rappen** [comment]
Thank you for reporting this!
Seems to be some cache bleeding...
