### ISSUE TITLE
"Cannot determine lookup entity, please enter Guid manually"

### ISSUE THREAD

**Issue by ovidiubechesamplexor** [rappen/FetchXMLBuilder#293]
Hello,

I try to set a filter condition, but I get that message. The Record textbox is readonly.

![image](https://user-images.githubusercontent.com/64836211/82814122-279fe380-9e9f-11ea-83a0-eff1a456152e.png)

Its a bug ? 

Ovidiu

**Comment by rappen** [comment]
It's a borderline case... the field isn't a lookup, since you appear to be filtering on the primary key of the `lnl_pos` entity.
Currently not a handled scenario, but you can access the classic way of entering guid manually by unchecking this option in the settings:
![image](https://user-images.githubusercontent.com/2572253/82815525-a42fc380-9e99-11ea-8330-337a64e56483.png)

I will keep this issue open to enable lookup dialog for primary keys too.
