### ISSUE TITLE
Would it be possible to change the color scheme in Fetch Xml editor to Classic from the Christmas theme with green elements?

### ISSUE THREAD

**Issue by xramow** [rappen/FetchXMLBuilder#335]

**Comment by xramow** [comment]
I'd like to use classic Xml color scheme
![image](https://user-images.githubusercontent.com/13473959/86768215-dcf4b800-c055-11ea-8878-6bd043862ee4.png)

**Comment by rappen** [comment]
That would be possible - once I implement the XMLViewer from https://github.com/jamesnovak/xrmtb.XrmToolBox.Controls instead of the custom implementation currently in FXB.
Stay tuned...
Not sure how long you'd have to stay tuned unfortunately - but it's on the roadmap now with this issue you created - thanks!

**Comment by rappen** [comment]
But I agree that the same theme should be used throughout the tool.

**Comment by xramow** [comment]
Thank you

**Comment by rappen** [comment]
Now possible any way you like it! 😁
![image](https://user-images.githubusercontent.com/2572253/88091616-9a6fc700-cb8f-11ea-855a-2c432a7c6cea.png)

Reset to get default colors:
![image](https://user-images.githubusercontent.com/2572253/88091573-87f58d80-cb8f-11ea-9807-a2efca0db7ef.png)

**Comment by xramow** [comment]
Awesome! Thank you!
