### ISSUE TITLE
"Cannot switch to tool SQL 4 CDS"

### ISSUE THREAD

**Issue by doneill2cc** [rappen/FetchXMLBuilder#567]
Hi there, 

I am trying to open SQL 4 CDS from Fetch XML Builder however when I try to do so I get the message "Cannot switch to tool SQL 4 CDS"

Any help would be massively appreciated. I have reset XRMToolbox, reinstalled both FetchXML Builder & SQL 4 CDS to no avail. It does switch to the SQL 4 CDS and that is where and when the error pops up. 

Thanks in advance, 
David

**Comment by MarkMpn** [comment]
Can you check what version of SQL 4 CDS you've got installed please? I believe this was fixed in 5.2.2

**Comment by doneill2cc** [comment]
Hi Mark, v5.2.3.0

**Comment by MarkMpn** [comment]
Found it - I've done the fix for this but not released it yet. New version should be coming out soon.

There is an option in SQL 4 CDS to remember your previous session - presumably at some point you closed SQL 4 CDS while two blank tabs were open, and now it's re-creating them each time you open it. Any unsaved tabs are just named "Query x", where x goes up each time a new tab is created in the session. If you want to get rid of one of these tabs, just close it before closing SQL 4 CDS. Alternatively, open the Settings dialog in SQL 4 CDS, go to the Editor tab and untick "Remember session details" so only a single blank tab will be opened each time regardless of what was last left open.

**Comment by doneill2cc** [comment]
May thanks Mark, appreciate the help!

Thanks,
David

**Comment by MarkMpn** [comment]
SQL 4 CDS 5.2.4 is now listed in XrmToolBox - please update  it and this problem should be resolved.

**Comment by doneill2cc** [comment]
Thanks Mark, all sorted
