### ISSUE TITLE
Error: 'The local name for elements or attributes...'

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#623]
Got the same error: 'The local name for elements or attributes cannot be null or empty' for all cloud crms. on-premise is ok.
error appears on plugin startup.

_Originally posted by @albert-halchanskiy in https://github.com/rappen/FetchXMLBuilder/issues/621#issuecomment-1014703360_

**Comment by beginner-luck1** [comment]
Hi all, sorry, new to GitHub, so I was wondering if there was a way to work around this error? Once this pops up, I can't do a thing with FetchXML.

**Comment by rappen** [comment]
Thanks @albert-halchanskiy and @beginner-luck1 too.
I need some more info - if you have it!
Have you the same issue with new version released Monday night (CET) version 1.2022.1.3?

**Comment by beginner-luck1** [comment]
Hi @rappen, 

Not very good at this, but please see what happens when I try to load the latest version of your app. 

It first brings up the below:
![Screenshot 2022-01-18 134330](https://user-images.githubusercontent.com/95251820/149948763-50d9ed30-d088-4894-8546-414a8819dcba.jpg)

Then it simply pops up with this:

![Screenshot 2022-01-18 134414](https://user-images.githubusercontent.com/95251820/149948841-9d14b433-c0fa-4cca-86b5-53b39c6bf11e.jpg)

The details from the error are:

[Error_details.txt](https://github.com/rappen/FetchXMLBuilder/files/7889490/Error_details.txt)

And this is all on the latest version of the app. It mainly happens when I try and open one of the saved xml searches I use all the time. The previous version, which I reinstalled using your excellent instructions let me continue as it was before.

If you are looking for much more, I will help where I can.

Thanks for your app, I use it a LOT!

Cheers,

**Comment by rappen** [comment]
Thanks @beginner-luck1 🙏

Can you also see the version?

![image](https://user-images.githubusercontent.com/2572253/149983333-b7caa1d6-cd70-4d9b-9b26-2ab8f50d832c.png)

Is it possible to send the fetchxml it is opening with?

**Comment by jxs0900** [comment]
I'm getting the same error as well

**Comment by beginner-luck1** [comment]
Hi @rappen,

Please see info below:

1.2021.10.2 - Is the version I use to make sure it is working

1.2022.1.3 - Is the version generating the errors.

XML search/code

<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
  <entity name="pwc_consent">
    <attribute name="pwc_channel" />
    <attribute name="pwc_startdate" />
    <attribute name="pwc_source" />
    <attribute name="pwc_enddate" />
    
    <order attribute="pwc_startdate" descending="true" />
    <filter type="and">
      <condition attribute="pwc_consentenum" operator="eq" value="1" />
      <condition attribute="pwc_agreed" operator="in">
        <value>1</value>
        <value>0</value>
      </condition>
      <condition attribute="statecode" operator="eq" value="0" />
    </filter>
    <link-entity name="contact" from="contactid" to="pwc_customerid" link-type="inner" alias="ak">
      <attribute name="pwc_carecontactid" />
      <filter type="and">
        <condition attribute="pwc_isfinancial" operator="eq" value="1" />
        <condition attribute="pwc_carecontactid" operator="in">
          <value>3296049</value>
          <value>4154739</value>
          <value>3315198</value>
          <value>193523</value>
        </condition>
      </filter>
    </link-entity>
  </entity>
</fetch>
