### ISSUE TITLE
Local Times option only works when Friendly Names is selected

### ISSUE THREAD

**Issue by markduk** [rappen/FetchXMLBuilder#628]
The "Local Times" appearance option only works when the "Friendly Names" option is selected.

**Comment by rappen** [comment]
Yes, that is right.
The gridview does only do it for "raw", here is the source line https://github.com/rappen/Rappen.XTB.Helper/blob/main/Controls/XRMDataGridView.cs#L241

I will look at this `XRMDataGridView` if I can get it better, otherwise to make it clear in FXB that you can't select that combination.

Thanks 🙏

**Comment by rappen** [comment]
Fixed for next release!
