### ISSUE TITLE
Repository should be rearranged

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#638]
See twitter:

![image](https://user-images.githubusercontent.com/2572253/152174888-bc961e54-fef4-4b8d-b087-2fc8cb44ea0b.png)
https://twitter.com/FetchXMLBuilder/status/1481653680696815623

It's not too used, I should rearrange the menus.

**Comment by bwmodular** [comment]
Seems a shame to hide this useful feature by default. I know lots of people don't seem to use it, but hiding it means that even less people will use it because they won't even know it's there. And for those of us who do use it, it's a 'now where's that gone' moment when we realise its missing....
But you did your research, and I'm very glad it's still there and VERY grateful for all of the amazing continuing work you carry out on the tool.
