### ISSUE TITLE
Unable to select date in latest version

### ISSUE THREAD

**Issue by BrettMNZWork** [rappen/FetchXMLBuilder#661]
Hi,
There seems to be some date validation issue when trying to use a date filter eg created on  1/13/2022.  I am based in New Zealand some my settings are for NZ time, so normally I would enter say 13th January 2022 as 13/1/2022.  If I do this I get a validation error saying date is out of range, use MM/DD/2022.  

No problem I can enter the date as 1/13/2022, however when I do that the 3 in the 13 gets removed so the date criteria goes to 1/1/2022 as shown in the attached file.

The query runs successfully but with the wrong data i.e. 1/1/2022 instead of 1/13/2022

![Data Validation Error](https://user-images.githubusercontent.com/23366759/155248918-8d4ce939-e5a5-460e-8fdf-f57d12991b08.png)

Cheers
Brett

**Comment by rappen** [comment]
I have no idea... 🙄
The conditions don't handle dates than other than text/string, int, etc...
It just takes what you write, and use that.

My format on my machine is (the best one 😏) ISO 8601 - but really it does not care about the format it uses.
See here:

![image](https://user-images.githubusercontent.com/2572253/155519278-78123752-097a-4691-911c-2905cc5b55a3.png)

So it is hard to understand why our `Value` is `1/13/2022` but the query gets `1/1/2022`.
Can I see the FetchXML too? Click the menu "View - FetchXML" to be shown. Add it here as "code", otherwise it does not be shown.

**Comment by BrettMNZWork** [comment]
Jonas,

Here is the fetch xml for

***@***.***

<fetch top="50">
  <entity name="g4a_accesscontrol">
    <attribute name="g4a_utid" />
    <attribute name="g4a_accesscontrolid" />
    <attribute name="g4b_accesspoint" />
    <attribute name="createdon" />
    <filter>
      <condition attribute="createdon" operator="on" value="1/3/2022" />
    </filter>
  </entity>
</fetch>

Note I also used 2022/1/30 i.e. yyyy/mm/dd and that worked as expected.

I will use that format in future.

Regards
Brett

**Comment by rappen** [comment]
Thanks.
Yes, the format is only related to the database format, not related to your locally format - as I think.

Close this issue now - please reopen it if it needs to look at more!
