### ISSUE TITLE
Query on audit + link entity to systemuser table does not display systemuser columns

### ISSUE THREAD

**Issue by MscrmTools** [rappen/FetchXMLBuilder#803]
I have the following query to display user access logs

```
<fetch top="50">
  <entity name="audit">
    <attribute name="objectid" />
    <attribute name="createdon" />
    <filter>
      <condition attribute="action" operator="eq" value="64" />
    </filter>
    <link-entity name="systemuser" from="systemuserid" to="objectid">
      <attribute name="fullname" />
    </link-entity>
  </entity>
</fetch>
```

The result in FetchXmlBuilder is 
![image](https://user-images.githubusercontent.com/10774317/198040638-b5244df3-c9b3-4e3d-8eae-09bf16d29159.png)

Whereas the same in FetchXmlTester produces the following result
![image](https://user-images.githubusercontent.com/10774317/198041038-9220a7a2-4506-4b13-8b1f-c3fe50f707cb.png)

**Comment by rappen** [comment]
You probably have "Layout" enabled in the settings.
I will improve the docs and the tool - but you need an alias on the link-entity. Otherwise it will not be possible to show the related attributes.

![image](https://user-images.githubusercontent.com/2572253/198048166-c20b59ca-d4a4-4550-9bd4-917810b4e1dd.png)
(sorry, no data in my environment, but you see the columns)

Try to disable Layout, everything will be shown.

**Comment by rappen** [comment]
Closing for now - please reopen if more issues!
