### ISSUE TITLE
Create QueryExpression with standard EarlyBound

### ISSUE THREAD

**Issue by rappen** [rappen/FetchXMLBuilder#808]
Today it only used late-bound for the generated code.
Make it optional to create early-bound code.

---
- Deployment: Online
- DB Version: 9.2.22101.170
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2022.11.59
- Tool Version: 1.2022.8.1

**Comment by bwmodular** [comment]
Hi Jonas, really liking the new EBG style queries for entity and column names. It'll make flipping back and forth between FXB and IDE much easier.
What would help even more would be if this could be extended to the use of Option Set Enums, such as:
`query.Criteria.AddCondition("statecode", ConditionOperator.Equal, (int)ContactState.Active);`

These are the EB features that are most useful, I think, because they not only help avoid typos but also help enormously in the readability of queries.
Is this doable? Is it something you'd consider? At the moment this is the biggest pain point for us using EBG as cutting and pasting between FXB and VS entails a lot of rewriting every time....
Thanks as ever for an amazing and every improving tool.

**Comment by rappen** [comment]
Totally agreement on that!

Implementing EBG has now got me to start thinking about, and actually right now working on it, to really do it Early Bound. Not only using the constants for "late bound code with constants", but using Daryl's [`QueryExpressionFactory`](https://github.com/daryllabar/DLaB.Xrm/blob/4a094f11d7ee0fa36f2090fce923314296d3ac3d/DLaB.Xrm.Core/QueryExpressionFactory.cs#L17) and Tanguy's [`FluentQueryExpression`](https://github.com/MscrmTools/MscrmTools.FluentQueryExpressions). That's more "early bound" than what we have today.

Would that look even better?
See #822 and #828.

Either way, I will try to implement Condition on OptionSet!
Would you like to create a new issue for that? 🙂

**Comment by bwmodular** [comment]
Thanks Jonas - I created https://github.com/rappen/FetchXMLBuilder/issues/829 for this.
