### ISSUE TITLE
Time out Issues Since Upgrade

### ISSUE THREAD

**Issue by MarcRohde** [rappen/FetchXMLBuilder#861]
I have noticed since updated to the latest version of FetchXML that I'm getting consistent timeout issues.

---
```
System.Net.WebException:
The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
System
- System.Net.HttpWebRequest.GetResponse()
- System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
```

---

```
<fetch top="10">
  <entity name="mserp_ecoresreleasedproductv2entity" />
</fetch>
```
---
- XrmToolBox Version: 1.2023.1.63
- FetchXML Builder Version: 1.2022.11.2
- DB Version: 9.2.22123.204
- Deployment: Online

**Comment by rappen** [comment]
I see more and more issue with connection too... 🫤
Do you know how long time it tasks between Execute and the error message shows up?

**Comment by MarcRohde** [comment]
> I see more and more issue with connection too... 🫤 Do you know how long time it tasks between Execute and the error message shows up?

I would guess it is 30 seconds or less.  It has started to happen every time I make an attempt to execute a query.

**Comment by rappen** [comment]
Thanks.
Do you know if `mserp_ecoresreleasedproductv2entity` is a **virtual** entity?

**Comment by MarcRohde** [comment]
> 

Yes, it is a virtual entity with Dynamics Finance and Operations.

**Comment by rappen** [comment]
I know virtual takes longer time...
I can't really find issues on my side, sorry.
Any ideas? Or is it just "the platform issues"...

**Comment by rappen** [comment]
I believe there is nothing to do about this issue. 
Please reopen if you have more info!

**Comment by alexveecode** [comment]
Has this issue when exporting notes/annotations. Worked fine when I tried a couple records, but complete export would fail. Turned out that it was a problematic attribute, "documentbody", which contains the base64-encoded attachment body (huge size). I guess the server-side doesn't like sending this much data and kills the connection.

Workaround was to skip this "documentbody" attribute in the exports. I'm guessing that setting the page size to something small and fetching only a few pages at a time could also work
