### ISSUE TITLE
Unhandled exception upon showing Both Names in result view

### ISSUE THREAD

**Issue by VeroslavOlic** [rappen/FetchXMLBuilder#963]
Hi,

I've just updated FetchXML to version 1.2023.8.2 and opened there a previously prepared view. When I tick the option Appearance - Both Names in the result view, it immediatelly shows an exception (bellow). When I leave Both Names unticked (and keep only Freindly Names on), then it works normally, without exception.

The exception text (attached, with screenshots) tells that the property DisplayIndex of DataGridViewColumn control must be smaller than the number of columns. Real value was 85.

Would you advise please?

Best rergards
Veroslav

[FetchXML unhandled exception.docx](https://github.com/rappen/FetchXMLBuilder/files/12428031/FetchXML.unhandled.exception.docx)

**Comment by rappen** [comment]
I thought I had fixed that type of issues... 😣
I can't reproduce the issue now.

Can you give me more info?
How to get the query/view - open a view from Dataverse? Or just remember that by default since last time?

Is FXB closed after the error message?
Is the whole XrmToolBox closed?
Or just continue after closing the error message?

Does this error appear always, with other queries as well?

Can you share your settings for FXB?
This is how to find them: https://app.screencast.com/392yzQzpZjr8K
There are two setting files:
* `Rappen.XTB.FXB_[Common].xml` with general setting.
* `Rappen.XTB.FXB_<name of the connection>.xml` is my demo I'm connected to `Jonas Space`.

**Comment by rappen** [comment]
I can now reproduce the issue!
Now I just have to find __*why*__ it happens...
Stay tuned...

**Comment by rappen** [comment]
You may test this fix now 🤓
Get this version here: https://1drv.ms/f/s!AjplCnpZdSjqn9VTdHUZXvfQUeopZQ?e=RlhaN6
Here is how to (just start on point 2): https://fetchxmlbuilder.com/manual-installation/

**Comment by VeroslavOlic** [comment]
Yes, that works 👍 I'm not getting the error anymore, even when I do switching "Both Names" on and off. Many thanks for your fast and great support rappen!
